module WishlistData
  class Ulduar
    include WishlistData

    active_difficulties :none

    difficulty :normal_10 do
      boss "Flame Leviathan" do
        item "Combustion Bracers"
        item "Energy Siphon"
        item "Firesoul"
        item "Firestrider Chestguard"
        item "Flamewatch Armguards"
        item "Gilded Steel Legplates"
        item "Handguards of Potent Cures"
        item "Ironsoul"
        item "Kinetic Ripper"
        item "Lifespark Visage"
        item "Mantle of Fiery Vengeance"
        item "Might of the Leviathan"
        item "Pyrite Infuser"
        item "Shimmering Seal"
        item "Twirling Blades"
      end

      boss "Ignis the Furnacemaster" do
        item "Armbraces of the Vibrant Flame"
        item "Drape of Fuming Anger"
        item "Furnace Stone"
        item "Gauntlets of the Iron Furnace"
        item "Gloves of Smoldering Touch"
        item "Igniter Rod"
        item "Pauldrons of Tempered Will"
        item "Relentless Edge"
        item "Rifle of the Platinum Guard"
      end

      boss "Razorscale" do
        item "Band of Draconic Guile"
        item "Binding of the Dragon Matriarch"
        item "Bracers of the Smothering Inferno"
        item "Breastplate of the Afterlife"
        item "Dragonsteel Faceplate"
        item "Eye of the Broodmother"
        item "Ironscale Leggings"
        item "Razorscale Talon"
        item "Stormtempered Girdle"
        item "Treads of the Invader"
      end

      boss "XT-002 Deconstructor" do
        item "Aesir's Edge"
        item "Armbands of the Construct"
        item "Breastplate of the Stoneshaper"
        item "Chestplate of Vicious Potency"
        item "Conductive Cord"
        item "Fluxing Energy Coils"
        item "Gloves of Taut Grip"
        item "Helm of Veiled Energies"
        item "Magnetized Projectile Emitter"
        item "Plasma Foil"
        item "Power Enhancing Loop"
        item "Pulsing Spellshield"
        item "Treacherous Shoulderpads"
        item "Vest of the Glowing Crescent"
      end

      boss "Kologarn" do
        item "Emerald Signet Ring"
        item "Greaves of the Earthbinder"
        item "Mark of the Unyielding"
        item "Pendant of the Piercing Glare"
        item "Sabatons of the Iron Watcher"
        item "Shawl of the Shattered Giant"
        item "Shoulderguards of the Solemn Watch"
        item "Spark of Hope"
        item "Spire of Withering Dreams"
        item "Stoneguard"
      end

      boss "Auriaya" do
        item "Archaedas' Lost Legplates"
        item "Chestplate of Titanic Fury"
        item "Cover of the Keepers"
        item "Elemental Focus Stone"
        item "Ironaya's Discarded Mantle"
        item "Mantle of the Preserver"
        item "Nimble Climber's Belt"
        item "Nurturing Touch"
        item "Raiments of the Corrupted"
        item "Shieldwall of the Breaker"
      end

      boss "Assembly of Iron" do
        item "Belt of the Crystal Tree"
        item "Belt of the Iron Servant"
        item "Boots of the Petrified Forest"
        item "Circlet of True Sight"
        item "Cloak of the Iron Council"
        item "Greaves of Iron Intensity"
        item "Lady Maye's Sapphire Ring"
        item "Leggings of Swift Reflexes"
        item "Loop of the Agile"
        item "Perilous Bite"
        item "Rune-Etched Nightblade"
        item "Runetouch Handwraps"
        item "Stormtip"
        item "The Masticator"
        item 45447 #Watchful Eye
      end

      boss "Hodir" do
        item "Avalanche"
        item "Bitter Cold Armguards"
        item "Cowl of Icy Breaths"
        item "Ice Layered Barrier"
        item "Icecore Staff"
        item "Leggings of the Wayward Conqueror"
        item "Leggings of the Wayward Protector"
        item "Leggings of the Wayward Vanquisher"
        item "Shiver"
        item "Signet of Winter"
        item "Stormedge"
        item "The Boreal Guard"
        item "Winter's Frigid Embrace"
      end

      boss "Thorim" do
        item "Belt of the Blood Pit"
        item "Combatant's Bootblade"
        item "Gauntlets of the Thunder God"
        item "Guise of the Midgard Serpent"
        item "Handwraps of Resonance"
        item "Hoperender"
        item "Legacy of Thunder"
        item "Leggings of Unstable Discharge"
        item "Mjolnir Runestone"
        item "Pendant of the Shallow Grave"
        item "Sif's Remembrance"
        item "Spaulders of the Wayward Conqueror"
        item "Spaulders of the Wayward Protector"
        item "Spaulders of the Wayward Vanquisher"
      end

      boss "Freya" do
        item "Chestguard of the Lasher"
        item "Fire Orchid Signet"
        item "Gloves of Whispering Winds"
        item "Gloves of the Wayward Conqueror"
        item "Gloves of the Wayward Protector"
        item "Gloves of the Wayward Vanquisher"
        item "Ironbark Faceguard"
        item "Legplates of Flourishing Resolve"
        item "Petrified Ivy Sprig"
        item "Seed of Budding Carnage"
        item "Serilas, Blood Blade of Invar One-Arm"
        item "Tunic of the Limber Stalker"
        item "Unraveling Reach"
      end

      boss "Mimiron" do
        item "Cable of the Metrognome"
        item "Fused Alloy Legplates"
        item "Fusion Blade"
        item "Greaves of the Iron Army"
        item "Helm of the Wayward Conqueror"
        item "Helm of the Wayward Protector"
        item "Helm of the Wayward Vanquisher"
        item "Mimiron's Flight Goggles"
        item "Pulse Baton"
        item "Shoulderguards of Assimilation"
        item "Static Charge Handwraps"
        item "Stylish Power Cape"
        item "Tempered Mercury Greaves"
      end

      boss "General Vezax" do
        item "Aesuga, Hand of the Ardent Champion"
        item "Bindings of the Depths"
        item "Boots of Unsettled Prey"
        item "Choker of the Abyss"
        item "Darkstone Ring"
        item "Drape of the Faceless General"
        item "Leggings of Profound Darkness"
        item "Pendant of Endless Despair"
        item "Saronite Animus Cloak"
        item "Shadowbite"
        item "Tortured Earth"
        item "Underworld Mantle"
        item "Vestments of the Piercing Light"
        item "Void Sabre"
      end

      boss "Yogg-Saron" do
        item "Abaddon"
        item "Amice of Inconceivable Horror"
        item "Caress of Insanity"
        item "Chestguard of the Wayward Conqueror"
        item "Chestguard of the Wayward Protector"
        item "Chestguard of the Wayward Vanquisher"
        item "Deliverance"
        item "Devotion"
        item "Faceguard of the Eyeless Horror"
        item "Hammer of Crushing Whispers"
        item "Kingsbane"
        item "Leggings of the Insatiable"
        item "Pendant of a Thousand Maws"
        item "Royal Seal of King Llane"
        item "Signet of Soft Lament"
        item "Soul-Devouring Cinch"
        item "Touch of Madness"
        item "Treads of the Dragon Council"
      end

      boss "Algalon the Observer" do
        item "Band of Lights"
        item "Breastplate of the Timeless"
        item 46038 #Dark Matter
        item "Drape of the Messenger"
        item "Gloves of the Endless Dark"
        item "Meteorite Crystal"
        item "Nebula Band"
        item "Observer's Mantle"
        item "Pendant of the Somber Witness"
        item "Pulsar Gloves"
        item "Reply-Code Alpha"
        item "Shoulderplates of the Celestial Watch"
        item "Starfall Girdle"
        item "Starlight Treads"
        item "Strength of the Heavens"
        item "Zodiac Leggings"
      end
    end

    difficulty :normal_25 do
      boss "Bind on Equip" do
        item "Asimov's Drape", "Mimiron"
        item "Cowl of the Absolute", "Auriaya"
        item "Darkcore Leggings", "General Vezax"
        item "Iron Riveted War Helm", "Flame Leviathan"
        item "Leggings of Lost Love", "Thorim"
        item "Leggings of the Stoneweaver", "Kologarn"
        item "Lifeforge Breastplate", "Ignis the Furnacemaster"
        item "Northern Barrier", "Hodir"
        item "Nymph Heart Charm", "Freya"
        item "Phaelia's Vestments of the Sprouting Seed", "Assembly of Iron"
        item "Proto-hide Leggings", "Razorscale"
        item "Signet of the Earthshaker", "XT-002 Deconstructor"
      end

      boss "Flame Leviathan" do
        item "Boots of Fiery Resolution", "Hard Mode"
        item "Constructor's Handwraps"
        item "Embrace of the Leviathan"
        item "Freya's Choker of Warding"
        item "Gloves of the Fiery Behemoth"
        item "Glowing Ring of Reclamation"
        item "Golden Saronite Dragon", "Hard Mode"
        item "Mechanist's Bindings"
        item "Mimiron's Inferno Couplings"
        item "Pendant of Fiery Havoc", "Hard Mode"
        item "Plated Leggings of Ruination", "Hard Mode"
        item "Shoulderpads of Dormant Energies", "Hard Mode"
        item "Steamcaller's Totem"
        item "Steamworker's Goggles"
        item "Strength of the Automaton"
        item "The Leviathan's Coil"
        item "Titanguard"
      end

      boss "Ignis the Furnacemaster" do
        item "Cindershard Ring"
        item "Flamestalker Boots"
        item "Flamewrought Cinch"
        item "Girdle of Embers"
        item "Heart of Iron"
        item "Helm of the Furnace Master"
        item "Intensity"
        item "Pyrelight Circle"
        item "Scepter of Creation"
        item "Soot-covered Mantle"
        item "Totem of the Dancing Flame"
        item "Worldcarver"
        item "Wristguards of the Firetender"
      end

      boss "Razorscale" do
        item "Belt of the Fallen Wyrm"
        item "Bracers of the Broodmother"
        item "Charred Saronite Greaves"
        item "Collar of the Wyrmhunter"
        item "Dragonslayer's Brace"
        item "Drape of the Drakerider"
        item "Guiding Star"
        item "Living Flame"
        item "Razorscale Shoulderguards"
        item "Remorse"
        item "Saronite Mesh Legguards"
        item "Shackles of the Odalisque"
        item "Sigil of Deflection"
        item "Veranus' Bane"
      end

      boss "XT-002 Deconstructor" do
        item "Boots of Hasty Revival"
        item "Brass-lined Boots"
        item "Breastplate of the Devoted", "Hard Mode"
        item "Charm of Meticulous Timing", "Hard Mode"
        item "Clockwork Legplates"
        item "Crazed Construct Ring"
        item "Gloves of the Steady Hand", "Hard Mode"
        item "Golem-Shard Sticker"
        item "Grasps of Reason", "Hard Mode"
        item "Horologist's Wristguards"
        item "Mantle of Wavering Calm"
        item "Quartz Crystal Wand"
        item "Quartz-studded Harness"
        item "Sandals of Rash Temperament"
        item "Shoulderplates of the Deconstructor"
        item "Sigil of the Vengeful Heart"
        item "Sorthalis, Hammer of the Watchers", "Hard Mode"
        item "Thunderfall Totem"
        item "Twisted Visage"
      end

      boss "Kologarn" do
        item "Bracers of Unleashed Magic"
        item "Decimator's Armguards"
        item "Giant's Bane"
        item "Gloves of the Pythonic Guardian"
        item "Handwraps of Plentiful Recovery"
        item "Idol of the Crying Wind"
        item "Ironmender"
        item "Malice"
        item "Necklace of Unerring Mettle"
        item "Robes of the Umbral Brute"
        item "Saronite Plated Legguards"
        item "Shoulderpads of the Monolith"
        item "Unfaltering Armguards"
        item "Wrathstone"
      end

      boss "Auriaya" do
        item "Amice of the Stoic Watch"
        item "Cloak of the Makers"
        item "Gloves of the Stonereaper"
        item "Greaves of the Rockmender"
        item "Libram of the Resolute"
        item "Platinum Band of the Aesir"
        item "Ring of the Faithful Servant"
        item "Runescribed Blade"
        item "Sandals of the Ancient Keeper"
        item "Shoulderplates of the Eternal"
        item "Siren's Cry"
        item "Stonerender"
        item "Unbreakable Chestguard"
        item "Unwavering Stare"
      end

      boss "Assembly of Iron" do
        item "Ancient Iron Heaume"
        item "Belt of Colossal Rage", "Hard Mode"
        item "Drape of Mortal Downfall", "Hard Mode"
        item "Drape of the Lithe"
        item "Fang of Oblivion", "Hard Mode"
        item "Greaves of Swift Vengeance", "Hard Mode"
        item "Handguards of the Enclave"
        item "Insurmountable Fervor"
        item "Iron-studded Mantle"
        item "Overload Legwraps"
        item "Radiant Seal"
        item "Raiments of the Iron Council"
        item "Rapture"
        item 45233 #Rune Edge
        item "Runed Ironhide Boots"
        item "Runeshaper's Gloves"
        item "Sapphire Amulet of Renewal", "Hard Mode"
        item "Shoulderpads of the Intruder", "Hard Mode"
        item "Steelbreaker's Embrace"
        item "Unblinking Eye"
      end

      boss "Hodir" do
        item "Bindings of Winter Gale", "Hard Mode"
        item "Breastplate of the Wayward Conqueror"
        item "Breastplate of the Wayward Protector"
        item "Breastplate of the Wayward Vanquisher"
        item "Constellus", "Hard Mode"
        item "Drape of Icy Intent", "Hard Mode"
        item "Frigid Strength of Hodir", "Hard Mode"
        item "Frost-bound Chain Bracers"
        item "Frostplate Greaves"
        item "Frozen Loop"
        item "Gloves of the Frozen Glade", "Hard Mode"
        item "Staff of Endless Winter", "Hard Mode"
        item "Winter's Icy Embrace"
      end

      boss "Thorim" do
        item "Belt of the Betrayed"
        item "Crown of the Wayward Conqueror"
        item "Crown of the Wayward Protector"
        item "Crown of the Wayward Vanquisher"
        item "Embrace of the Gladiator", "Hard Mode"
        item "Fate's Clutch", "Hard Mode"
        item "Pauldrons of the Combatant", "Hard Mode"
        item "Scale of Fates"
        item "Sif's Promise"
        item "Skyforge Crossbow"
        item "Vulmir, the Northern Tempest"
        item "Warhelm of the Champion", "Hard Mode"
        item "Wisdom's Hold", "Hard Mode"
      end

      boss "Freya" do
        item "Bladetwister", "Hard Mode"
        item "Boots of the Servant"
        item "Bronze Pendant of the Vanir", "Hard Mode"
        item "Drape of the Sullen Goddess", "Hard Mode"
        item "Dreambinder", "Hard Mode"
        item "Gauntlets of Ruthless Reprisal"
        item "Handguards of Revitalization", "Hard Mode"
        item "Leggings of the Enslaved Idol", "Hard Mode"
        item "Leggings of the Lifetender"
        item "Legplates of the Wayward Conqueror"
        item "Legplates of the Wayward Protector"
        item "Legplates of the Wayward Vanquisher"
        item "The Lifebinder"
      end

      boss "Mimiron" do
        item "Armbands of Bedlam", "Hard Mode"
        item "Conductive Seal", "Hard Mode"
        item "Crown of Luminescence", "Hard Mode"
        item "Delirium's Touch", "Hard Mode"
        item "Gauntlets of the Wayward Conqueror"
        item "Gauntlets of the Wayward Protector"
        item "Gauntlets of the Wayward Vanquisher"
        item "Insanity's Grip"
        item "Malleable Steelweave Mantle"
        item "Pandora's Plea"
        item "Titanskin Cloak", "Hard Mode"
        item "Starshard Edge", "Hard Mode"
        item "Waistguard of the Creator"
      end

      boss "General Vezax" do
        item "Belt of Clinging Hope"
        item "Belt of the Darkspeaker"
        item "Boots of the Forgotten Depths"
        item "Boots of the Underdweller"
        item "Flare of the Heavens", "Hard Mode"
        item "Grips of the Unbroken"
        item "Handwraps of the Vigilant", "Hard Mode"
        item "Helm of the Faceless"
        item "Idol of the Corruptor"
        item "Libram of Discord"
        item "Libram of the Sacred Shield"
        item "Lotrafen, Spear of the Damned"
        item "Mantle of the Unknowing"
        item "Metallic Loop of the Sufferer"
        item "Pendulum of Infinity", "Hard Mode"
        item "Ring of the Vacant Eye"
        item "Scepter of Lost Souls"
        item "The General's Heart"
        item "Vestments of the Blind Denizen", "Hard Mode"
        item "Voldrethar, Dark Blade of Oblivion", "Hard Mode"
      end

      boss "Yogg-Saron" do
        item "Blood of the Old God"
        item "Chestguard of Insidious Intent"
        item "Chestguard of the Fallen God"
        item "Cowl of Dark Whispers"
        item "Dark Edge of Depravity", "Hard Mode"
        item "Earthshaper"
        item "Garona's Guise"
        item "Godbane Signet"
        item "Legguards of Cunning Deception", "Hard Mode"
        item "Mantle of the Wayward Conqueror"
        item "Mantle of the Wayward Protector"
        item "Mantle of the Wayward Vanquisher"
        item "Sanity's Bond"
        item "Seal of the Betrayed King", "Hard Mode"
        item "Shawl of Haunted Memories"
        item "Show of Faith", "Hard Mode"
        item "Soulscribe"
        item "Treads of the False Oracle", "Hard Mode"
        item "Vanquished Clutches of Yogg-Saron"
      end

      boss "Algalon the Observer" do
        item "Boundless Gaze"
        item "Bulwark of Algalon"
        item "Comet's Trail"
        item "Constellus"
        item "Cosmos"
        item "Dreambinder"
        item "Fang of Oblivion"
        item "Legplates of the Endless Void"
        item "Pharos Gloves"
        item "Reply-Code Alpha"
        item "Sabatons of Lifeless Night"
        item "Skyforge Crossbow"
        item "Solar Bindings"
        item "Star-beaded Clutch"
        item "Starshard Edge"
        item "Starwatcher's Binding"
      end
    end
  end
end
